### PR TITLE
Fix name for Monument

### PR DESCRIPTION
**Pull request by seg-on**
Change slovak name for Monument from 'pamätník' to 'pamätihodnosť'

### CODE REVIEW

**Comment by zdila** [comment]
I think it should be "Pomník"

**Comment by seg-on** [comment]
OK, I took this name 'Pamätihodnosť' because it is use in feature Object (POI)
I think it would be nice have unificet name for the same tag Monument.
image
Therefore would be good rename 'Pamätihodnosť' to 'Pomník' in Object (POI) too.

**Comment by zdila** [comment]
> Therefore would be good rename 'Pamätihodnosť' to 'Pomník' in Object (POI) too.

I agree. https://github.com/FreemapSlovakia/freemap-v3-react/blob/develop/src/translations/sk.tsx#L658

**Comment by zdila** [comment]
why did you close it?

**Comment by seg-on** [comment]
Because this Pull Request include bad changes. I think another changes need new commit and new Pull Request. No?

**Comment by zdila** [comment]
After squashind it only contain single change: https://github.com/FreemapSlovakia/freemap-mapnik/pull/167/files

**Pull request closed without merging**
