### PR TITLE
Added icon for natural=stone

### PR DESCRIPTION
**Pull request by seg-on**
Added icon for natural=stone
source https://svgsilh.com/image/308734.html

### CODE REVIEW

**Review by zdila — CHANGES_REQUESTED** [review]
Please make icon smaller.

Also:
* compress it using https://jakearchibald.github.io/svgomg/ (or its commandline verison)
* get rid of all namespaces and proprietary tags (except http://www.w3.org/2000/svg of course)
* don't use`viewBox` attribute
* use pixels, not points (pt)
* don't use transforms

**Comment by seg-on** [comment]
what's the problem with _viewBox_ ?
I see it in many other SVG here.

**Comment by zdila** [comment]
What is `kresba.svg`? alsp `px` is default - no need to specify unit.

**Comment by seg-on** [comment]
`kresba.svg` is my fault. it was temporary file due making simplify stone.svg You can discard it.

**Comment by zdila** [comment]
just delete it and commit :-)

**Comment by zdila** [comment]
btw now the drawing in svg is pretty huge, probably because of removing viewBox but not adjusting dimensions. i will take a look by myself.

**Pull request merged**
