### PR TITLE
Update legend.js

### PR DESCRIPTION
**Pull request by dp7x**
added it: ' ...'   till line 435
Please check if I am doing right or something is missing

### CODE REVIEW

**Comment by dp7x** [comment]
translated till line 825

please somebody check if I am doing good with the code, thanx

**Comment by dp7x** [comment]
translation complete,  pull request can be closed

**Comment by zdila** [comment]
@dp7x thank you! I have deployed it to the production.

**Comment by dp7x** [comment]
👍👍

Diego

Il giorno 11 giu 2022, alle ore 06:42, Martin Ždila ***@***.***> ha scritto:

﻿

@dp7x<https://github.com/dp7x> thank you! I have deployed it to the production.

**Pull request merged**
